Create pr-check.yml
Xkonti/govec pull request #42
Opened 2023-10-08 09:07 UTC by Pr0-C0der

Created Github actions workflow for Fixes #41. 

While testing runs all files with the suffix "_test.go", and does not merge the PR if any test fails. 

To create a message on the Pull Request, I need a GitHub personal access token with permission to write the message to notify the user about the error.

2023-10-08 15:41 UTC, Xkonti commented
@Pr0-C0der Looks good. You can use `PR_TOKEN` secret to get the token.

2023-10-09 06:33 UTC, Xkonti requested changes
Nice job with the comment!

2023-10-09 06:33 UTC, Xkonti commented on .github/workflows/pr-check.yml
> +      - main
This shouldn't be here. Merges to `main` are prohibited and ALL changes happen through PRs.

2023-10-09 06:33 UTC, Xkonti commented on .github/workflows/pr-check.yml
> +# This workflow will build a golang project
This workflow will build `and test` the library

2023-10-09 13:37 UTC, Pr0-C0der commented
Please review @Xkonti. I was having issues with commenting stuff, so I decided to remove it. Nevertheless, when 'go test' command runs it will automatically tell the user which test file failed and on which line.

2023-10-09 16:25 UTC, merged